const ValidEmail=["@gmail.com","@yahoo.com","@yahoo.co.uk","@outlook.com","@hotmail.com","@live.com","@icloud.com","@me.com","@aol.com","@protonmail.com","@zoho.com","@mail.com","@gmx.com","@yandex.com"]
const StockjVinil = ["#FF0000","#00FF00","#0000FF","#FFFF00","#FF00FF","#00FFFF","#FFA500","#A52A2A","#800080","#000000","#FFFFFF","#808080"]

const CopyPresset = {
    Pix:`
  Chave: 81987265401
  Nome: Alan Ferreira da Silva`
}

const UsEr={
  '34$r4-34&-7eV79@7K':['(Baby)','Baby Massia','Img/Perfil_Baby.png'],
  '31$r1-31&-4eV49@4K':['(Alan)','Allan MacLovin','Img/Perfil_Allan.png'],
  '32$r2-32&-6eV69@6K':['(Lisa)','Lisa Caramelo','Img/Perfil_Lisa.png'],
  '36$r6-36&-9eV99@9K':['(Segu)','Segunda Hippie','Img/Perfil_Segunda.png'],
  'Login'             :[''      ,'Login'         ,'./Img/LogOff.png']
}

const TM = {
     Edi :'contenteditable="true"'
    ,Err :`onerror="this.src='./SVG/placeholder.svg'"`
    ,Pss:'Senha Inválida'
}
const Mnsg  = {PreTbl:(Typ)=>`A Tabela ${Typ} já estava Carregada...`}

// todos tem q ter pre e pos
// 'Pre' : 'https://www.mercadopago.com.br/activities/detail/'
// 'pos' : '?from=activities-frontend'
// 'mo'   : 'pix_transfer_mo_payout_movement-'
// 'mi'   : 'pix_transfer_mi_movement-'
// 'ch'   : 'checkout_merchant_order-'
// 'qr'   : 'instore_pix_qr-'
// 'qrm'  : 'qr_merchant_order-'
// 'trn'  : 'pix_transfer_mo_payment_movement-'
// 'pay'  : 'pix_payment_mo_payout_movement-'
// 'sig'  : 'single_player_prepaid-'
// 'card' : 'mp_card-'
// 'Cry'  : 'investment_crypto_bhs-'
// 'non'  : 'non_transactional-'
// 'deb'  : 'debt_notifications-'

const Ramos = {
  'Alimentos e Bebidas': {
      Comr:['Padaria','Depósito de Bebidas','Depósito de Água e Gás','Mercadinho','Frigorifico & Peixe','Frutas & Verduras','Empório','Ração'],
      CoSv:['Churrascaria','Restaurante','Lanchonete','Bar','Bistrô & Café','Buffet','Sorveteria','Barraca Lanche','Conveniência','Açaíteria','Tapiocaria','Pizzaria','Temakeria','Casa de Bolo','Confeiteiro'],
      Fabr:['Fábrica de Sorvete']
  },'Vendas e Objetos': {
      Comr:['Arte e Antiguidades','Artigos Religiosos','Bebês e Cia','Brinquedos e Games','Casa e Decoração','Colecionáveis','Cosméticos e Perfumaria','Eletrodomésticos','Fotografia','Flores, Cestas e Presentes','Instrumentos Musicais','Joalheria','Livros','Funerários','Variedades','Gráfica','Papelaria e Escritório','Místicos']
  },'Estétia e Moda': {
      Comr:['Sapatos','Roupas e Acessórios','Sex Shop'],
      Serv:['Salão Cabeleireiro','Sobrancelha','Unha em Gel','Barbearia','Tatuagem']
  },'Técnologia': {
      Comr:['Informática','Assesórios Celular','Eletrônica'],
      Serv:['Internet','Téc. Refrigeração'],
      'Comércio/Serviço': ['Equipadora Som','Assistência Téc. PC','Assistência Téc. Celular']
  },'Saúde e Medicamento': {
      Serv:['Nutrição','Pscicologia','Laboratório e Exame','Odontologia'],
      Comr:['Farmácia'],
      CoSv:['Vetrinário']
  },'Construção e Ferramentas': {
      Serv:['Serralharia','Marcenaria','Pedreiro','Engenharia','Eletricista','Encanação'],
      CoSv:['Gesso'],
      Comr:['Armazém']
  },'Serviços Pessoais': {
      Serv:['Seguradora','Segurança','Transporte','Turismo','Motéis','Aluguel e Locações']
  },'Instituições': {
      Serv:['Associações','Advocacia','Cartórios','Bibliotecas','Casas Lotéricas','Consórcios','Cooperativas','Emissoras de Rádio','Emissoras de Televisão','Instituições Religiosas','Prefeitura']
  },'Educação': {
      Serv:['Escola','Curso']
  },'Serviço': {
      Serv:['Estacionamentos','limpeza','Ecologia','Agricultura','Festas & Eventos','Mecânico','Costureira','Serviços Gráficos','Pet Shop']
  }
}

const ListARQ = [
    "101_1",
    "103_1",
    "108_1",
    "109_1",
    "110_1",
    "117_1",
    "124_1",
    "128_3",
    "131_2",
    "133_1",
    "134_1",
    "136_1",
    "139_1",
    "140_1",
    "144_3",
    "153_1",
    "155_1",
    "169_1",
    "170_1",
    "170_2",
    "171_1",
    "172_1",
    "173_1",
    "174_1",
    "184_1",
    "184_2",
    "185_2",
    "193_1",
    "195_1",
    "204_1",
    "231_1",
    "234_1",
    "235_1",
    "236_1",
    "240_1",
    "243_1",
    "251_1",
    "255_1",
    "261_1",
    "271_4",
    "277_4",
    "278_1",
    "279_10",
    "280_1",
    "281_1",
    "81_1",
]

const Fonts = ["Arial", "Courier New", "Georgia", "Times New Roman", "Verdana", "Comic Sans MS", "Trebuchet MS", "Impact", "Lucida Console", "Tahoma", "Helvetica", "Palatino Linotype", "Frank Ruhl Libre", "Montserrat", "Open Sans"]
const KitFonts = [
    'advent-Bd1',
    'advent-Bd2',
    'advent-Bd3',
    'advent-Lt1',
    'advent-Lt2',
    'advent-Lt3',
    'advent-Re',
    'Almarose-Black',
    'Almarose-Bold',
    'Almarose-ExtraBlack',
    'Almarose-Extrabold',
    'Almarose-Light',
    'Almarose-Medium',
    'Almarose-Regular',
    'Almarose-Semibold',
    'Almarose-Thin',
    'Anja Eliane accent002',
    'arial-rounded-mt-bold',
    'Balbek-Personal Use Only',
    'BebasNeue-Regular',
    'BebasNeue-Regular',
    'Dunkin Bold',
    'Dunkin Sans Bold',
    'EngraversGothic BT',
    'Exotc350 Bd BT Bold',
    'Exotc350 DmBd BT Demi-Bold',
    'Futura Bk BT Book',
    'Futura Bold BT',
    'Futura Bold Condensed BT',
    'Futura Light Condensed BT',
    'Futura Md BT Bold',
    'Futura Md BT Medium',
    'Futura Medium Condensed BT',
    'Futura-Condensed-Bold',
    'Futura-Condensed-Normal',
    'Futura-Condensed-Thin',
    'Futura-CondensedExtraBold-Th',
    'Futura-CondensedLight-Normal',
    'Futura-CondensedLight-Thin',
    'Futura-Normal',
    'FuturaCnd-Bold',
    'FuturaCnd-Norma',
    'FuturaCondLightE Regular',
    'Geometr212 BkCn BT Book',
    'Geometr212 BkCn BT Heavy',
    'Geometr415 Blk BT Black',
    'Geometr706 BlkCn BT Black',
    'GlacialIndifference-Bold',
    'GlacialIndifference-Regular',
    'Gotham Black Regular',
    'gotham-black',
    'holomdl2',
    'Humanst521 BT Bold',
    'Humanst521 BT Roman',
    'Humanst521 Lt BT Light',
    'Humnst777 BlkCn BT Black',
    'Humnst777 BT Roman',
    'Humnst777 Cn BT Bold',
    'Humnst777 Cn BT',
    'Humnst777 Lt BT Light',
    'IN901XKI',
    'Insanibc',
    'Insanibu',
    'integral-cf-medium',
    'Netraly',
    'neuzeitgrotblaextcon',
    'NewsGoth BT Bold',
    'NewsGoth BT Roman',
    'NewsGoth Lt BT Light',
    'ntailu',
    'ntailub',
    'OCR-B 10 BT',
    'phagspa',
    'phagspab',
    'Square721 BT Bold',
    'Square721 BT Roman',
    'Square721 Cn BT Bold',
    'Square721 Cn BT Roman',
    'Swis721 Blk BT Black',
    'Swis721 BlkCn BT Black',
    'Swis721 BT Bold',
    'Swis721 BT Roman',
    'Swis721 Cn BT Bold',
    'Swis721 Cn BT Roman',
    'Swis721 Hv BT Heavy',
    'Swis721 Lt BT Light',
    'Swis721 LtEx BT Light',
    'Swis721 WGL4 BT Bold',
    'Swis721 WGL4 BT Roman',
    'taile',
    'taileb',
    'Black-coffee-shadow',
    'Black-coffee',
    'CFGlitchCity-Regular',
    'CoffeCake',
    'Empires',
    'Freehand521 BT',
    'Gloomy Things',
    'Jacksilver',
    'Jamstreet Graffiti',
    'KOMIKAX_',
    'Malvie Trial',
    'MARSNEVENEKSK-Clean',
    'Mermaid Babies',
    'Mustard Smile',
    'Sandler Trial',
    'SOUTH-CREW',
    'Starlight',
    'Starlight',
    'Study Alone',
    'Thunder Bold',
    'Trolls Movie Font',
    'True Lies',
    'waltograph42',
    'waltographUI',
    'whoa!',
    'Fluo Gums',
    'GAGARIN_',
    'GAGASM__',
    'Gobold Blocky Regular',
    'Good Morning',
    'Jackpot Demo',
    'KGHAPPYSolid',
    'Legend M54',
    'Magnificent Personal Use',
    'Amsterdam',
    'April June',
    'Austria',
    'Bacalisties',
    'Blacksword',
    'boutiera-regular',
    'BrushScriptOpti-Regular',
    'buttercup_sample',
    'Caroline',
    'Contoursy Free',
    'Cream Cake',
    'Delight Sunset',
    'dk-combustible-regular',
    'Embassy BT',
    'exmouth',
    'FontsFree-Net-MoonTime-Regular-1',
    'Gillian Rode',
    'Halimun',
    'harlow-solid-std',
    'Howell Rode',
    'Kaufmann BT',
    'LOKICOLA',
    'Madina',
    'Manly Signature Regular',
    'Maria Aishane Script',
    'Maria Aishane Script',
    'Maria_lucia',
    'Pantherdam Signature',
    'Pinky Promise',
    'PinkyPromise',
    'Ruthligos',
    'Streamster',
    'Summer Lightning Demo',
    'The Golden Elephant',
    'The Yoshi',
    'TypoUpright BT',
    'Weather Sunday - Personal Use',
    'Meatloaf Solid',
    'PWYummyDonuts',
    'Quark Cheese - Personal Use',
    'Quillain (DEMO)',
    'Quillain (DEMO)',
    'RifficFree-Bold',
    'Rightland',
    'Run! Demo',
    'aachen-bold',
    'AgreloyInT3',
    'Ancient Medium',
    'atwriter',
    'belwe-std-condensed',
    'BerkshireSwash-Regular',
    'bernard-mt-std-condensed',
    'Bodoni Bd BT Bold',
    'Bodoni Bk BT Book',
    'CentSchbkCyrill BT Bold Italic',
    'CentSchbkCyrill BT Bold',
    'CentSchbkCyrill BT Italic',
    'CentSchbkCyrill BT Roman',
    'Century Oldstyle Bold',
    'Century Oldstyle Italic',
    'Century Oldstyle Regular',
    'Century725 Cn BT',
    'Century751 BT Italic',
    'Century751 BT Roman',
    'Century751 No2 BT Bold Italic',
    'Century751 No2 BT Bold',
    'Century751 No2 BT Italic',
    'Century751 No2 BT Roman',
    'Century751 SeBd BT Semi Bold Italic',
    'Century751 SeBd BT Semi Bold',
    'Clarendon Blk BT Black',
    'Clarendon BT Bold',
    'Clarendon BT Roman',
    'Clarendon Lt BT Light',
    'Cloister Oldstyle Roman',
    'CloisterBlack',
    'DeVinne Txt BT',
    'Edensor-FREE',
    'FE-FONT',
    'FONTLERO',
    'GeoSlab703 Md BT Bold',
    'GeoSlab703 Md BT Medium',
    'GeoSlab703 MdCn BT Bold',
    'GeoSlab703 MdCn BT Medium',
    'Home Christmas',
    'Hundo',
    'IFC INSANE RODEO BOLD Bold',
    'IFC INSANE RODEO',
    'MADEAvenuePERSONALUSE-Regular',
    'MAK-bold',
    'MAK',
    'News701 BT Bold',
    'News701 BT Italic',
    'News706 BT Bold',
    'OCR-A BT',
    'Olondona',
    'PirataOne-Regular',
    'PlateGtFourMTStd-Bd',
    'Qeilab',
    'RalstedaBold-d9d56',
    'RalstedaExtralight-L3vAg',
    'RalstedaHeavy-gxX2Y',
    'RalstedaLight-X3RXo',
    'RalstedaMedium-owAxV',
    'RalstedaRegular-4Bqy9',
    'Saddlebag',
    'Schadow BT Bold',
    'Schadow BT Roman',
    'Seagram tfb',
    'symbol',
    'TequilaSunrise-Regular',
    'TEXAT BOLD PERSONAL USE___',
    'TrajanPro-Bold',
    'TrajanPro-Regular',
    'VarsityTeam-Bold',
    'VASTN___',
    'Smartphone Color Pro',
    'Social Logos',
    'Splatch',
    'Stella Demo',
    'Stella Demo',
    'airstrike',
    'airstrike3d',
    'airstrikeacad',
    'airstrikeb3d',
    'airstrikebold',
    'airstrikebullet',
    'airstrikecond',
    'airstrikeexpand',
    'airstrikegrad',
    'airstrikehalf',
    'airstrikelaser',
    'airstrikeout',
    'Clark Bold Hollow',
    'Clark Bold',
    'Clark Hollow',
    'Clark',
    'DEADJIM',
    'Digital-Desolation-Plus',
    'Dihil',
    'Elektronik Italic',
    'Elektronik',
    'FontsFree-Net-Nura-ExtraLight',
    'High Speed',
    'Hindsight 2020',
    'hyperspace-race-extended-heavy',
    'Inlanders Demo',
    'Kardust TS Condensed Bold Italic',
    'KITCHENPOLICE',
    'LinkStart',
    'osaka-re',
    'paladins',
    'paladins3d',
    'paladinsgrad',
    'paladinslaser',
    'paladinsout',
    'paladinsstraight',
    'pricedown bl',
    'Reckoner',
    'Reckoner_Bold',
    'Rektec',
    'SOLVAST',
    'Square',
    'SwipeRaceDemo',
    'techno_hideo',
    'Vudotronic',
    'zrnic rg',
    'The Blacklist',
    'Type Icons',
    'aAttackGraffiti',
    'Comix Loud',
    'Dunkin Sans',
    'Dunkin',
    'Gemstone',
    'GROBOLD',
    'Irresponsible Direction',
    'Karate',
    'lastninja',
    'Minnie',
    'mvboli',
    'Neonblitz',
    'PlazaITC-Normal',
    'Rockit',
    'RUSTY ATTACK DEMO Regular',
    'seasideresortnf.regular',
    'shanghai',
    'TheGeorgia',
    'varsity_regular',
    'Wicked Mouse Demo',
    'xilosa',
]