const DadosGRAD = [
    {
        "ID": 1,
        "Emal": "423° Grafit - 0312",
        "Data": "",
        "Forn": "Grafit",
        "OS": "OS-009190",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ads(Rct) 1,00 x 0,67",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["14_1"],
            }
        ],
        "Lixo": ""
    },
    {
        "ID": 2,
        "Emal": "424° Grafit - 0412",
        "Data": "",
        "Forn": "BPrint",
        "OS": "OS-009190",
        "Grad": "", "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ads(Rct) 1,00 x 1,00",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["25_1"],
            },
            {
                "Id": 'B',
                "Nome": "1 - Ads(Rct) 1,00 x 0,77",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["25_2"],
            },
            {
                "Id": 'C',
                "Nome": "1 - Ads(Blh) 1,00 x 1,00",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["25_3", "19_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 3,
        "Emal": "425° Grafit - 0612",
        "Data": "",
        "Forn": "",
        "OS": "Sem OS",
        "Grad": "", "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ilhós 1,46 x 0,48",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": [""],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 4,
        "Emal": "426° Grafit - 0912",
        "Data": "",
        "Forn": "",
        "OS": "OS-009213",
        "Grad": "", "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Faixa - 1,46 x 0,48",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["28_1"],
            },

        ],
        "Lixo": ""
    },
    {
        "ID": 5,
        "Emal": "427° Grafit - 0912",
        "Data": "",
        "Forn": "",
        "OS": "OS-009213",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ads(Blh) 1,00 x 0,70",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["40_1"],
            },
            {
                "Id": 'B',
                "Nome": "1 - Ads(Blh) 1,00 x 1,60",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["45_2"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 6,
        "Emal": "428° Grafit - 1012",
        "Data": "",
        "Forn": "",
        "OS": "OS-009213",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Bnnr 0,65 x 1,60",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["45_3"],
            },
            {
                "Id": 'B',
                "Nome": "1 - Bnnr 0,70 x 1,10",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["78_2"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 7,
        "Emal": "429° Grafit - 1112",
        "Data": "",
        "Forn": "",
        "OS": "Manual1",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ads(Blh) 1,00 x 12,00",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["46_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 8,
        "Emal": "087° BPrint - 0312",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ads(Blh) - 1,00 x 0,70",
                "Desc": "",
                "QntS": "3",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["3_1", "5_1", "1_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 9,
        "Emal": "088° BPrint - 0312",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Bnnr 1,00 x 1,00",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["15_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 10,
        "Emal": "089° BPrint - 0312",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Colchê Adesivo (A3 Lazer)",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["56_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 11,
        "Emal": "090° BPrint - 0612",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ads(Blh) 1,00 x 0,55",
                "Desc": "",
                "QntS": "2",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["36_1", "52_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 12,
        "Emal": "091° BPrint - 1012",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ads(Blh) 1,00 x 0,43",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["42_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 13,
        "Emal": "092° BPrint - 1012",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "4 - Triplex Branco 250g Brilho",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["30_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 14,
        "Emal": "093° BPrint - 1112",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ads(Blh) 1,00 x 1,80",
                "Desc": "",
                "QntS": "4",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["34_2", "53_1", "55_1", "49_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 15,
        "Emal": "094° BPrint - 1312",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ads(Rct) 1,00 x 0,55",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["50_1"],
            },
            {
                "Id": 'B',
                "Nome": "1 - Ads(Blh) 1,00 x 1,00",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["51_1"],
            }
        ],
        "Lixo": ""
    },
    {
        "ID": 16,
        "Emal": "095° BPrint - 1612",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ads(Blh) 1,00 x 0,50",
                "Desc": "",
                "QntS": "2",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["60_1", "58_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 17,
        "Emal": "096° BPrint - 1612",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Triplex Branco 250g",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["63_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 18,
        "Emal": "097° BPrint - 1812",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "", "Cont": "", "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Triplex Branco 250g",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["75_1"],
            },
            {
                "Id": 'B',
                "Nome": "6 - Colchê 90g Plastificado",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["82_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 19,
        "Emal": "098° BPrint - 2012",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ads(Blh) 1,00 x 1,05",
                "Desc": "",
                "QntS": "2",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["72_2"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 20,
        "Emal": "099° BPrint - 2212",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "2 - Triplex Branco 250g",
                "Desc": "",
                "QntS": "1",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": [""],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 21,
        "Emal": "430° Grafit - 1712",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "1 - Ads(Blh) 1,00 x 0,55",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["67_1"],
            },
        ],
        "Lixo": ""
    },
    {
        "ID": 22,
        "Emal": "431° Grafit - 1812",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD":
            [
                {
                    "Id": 'A',
                    "Nome": "1 - Ads(Blh) 1,01 x 2,40",
                    "Desc": "",
                    "QntS": "",
                    "Valr": "",
                    "Uber": "",
                    "VUbr": "",
                    "Link": ["72_1"],
                },
                {
                    "Id": 'B',
                    "Nome": "1 - Banner 0,80 x 1,20",
                    "Desc": "",
                    "QntS": "",
                    "Valr": "",
                    "Uber": "",
                    "VUbr": "",
                    "Link": ["74_1"],
                }
            ],
        "Lixo": ""
    },
    {
        "ID": 23,
        "Emal": "SANTO",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": ["83_1"],
            }],
        "Lixo": ""
    },
    {
        "ID": 24,
        "Emal": "432° Grafit - 3012",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "", "Cont": "", "ABCD": [
            {
                "Id": 'A',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": [""],
            }],
        "Lixo": ""
    },
    {
        "ID": 25,
        "Emal": "433° Grafit - 0601",
        "Data": "",
        "Forn": "",
        "OS": "OS-009292",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "40,00",
                "Uber": "23",
                "VUbr": "R$ 2,75",
                "Link": [""],
            }],
        "Lixo": ""
    },
    {
        "ID": 26,
        "Emal": "434° Grafit - 0601",
        "Data": "",
        "Forn": "",
        "OS": "OS-009292",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "36,00",
                "Uber": "23",
                "VUbr": "R$ 2,75",
                "Link": [""],
            }],
        "Lixo": ""
    },
    {
        "ID": 27,
        "Emal": "435° Grafit - 0701",
        "Data": "",
        "Forn": "",
        "OS": "OS-009292",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "15,00 _ 73,50 _ 30,33",
                "Uber": "23",
                "VUbr": "R$ 2,75",
                "Link": [""],
            },
            {
                "Id": 'B',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "23",
                "VUbr": "R$ 2,75",
                "Link": [""],
            },
            {
                "Id": 'C',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "23",
                "VUbr": "R$ 2,75",
                "Link": [""],
            }
        ],
        "Lixo": ""
    },
    {
        "ID": 28,
        "Emal": "436° Grafit - 0701",
        "Data": "",
        "Forn": "",
        "OS": "OS-009292",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "42,00 _ 7,60",
                "Uber": "23",
                "VUbr": "R$ 2,75",
                "Link": [""],
            },
            {
                "Id": 'B',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": [""],
            },

        ],
        "Lixo": ""
    },
    {
        "ID": 29,
        "Emal": "437° Grafit - 0801",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": [""],
            },
            {
                "Id": 'B',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": [""],
            },
            {
                "Id": 'C',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": [""],
            },

        ],
        "Lixo": ""
    },
    {
        "ID": 30,
        "Emal": "100° BPrint - 0901",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": [""],
            }],
        "Lixo": ""
    },
    {
        "ID": 31,
        "Emal": "101° BPrint - 0901",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": [""],
            }],
        "Lixo": ""
    },
    {
        "ID": 32,
        "Emal": "438° Grafit - 0901",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": [""],
            }],
        "Lixo": ""
    },
    {
        "ID": 33,
        "Emal": "439° Grafit - 1001",
        "Data": "",
        "Forn": "",
        "OS": "",
        "Grad": "",
        "Cont": "",
        "ABCD": [
            {
                "Id": 'A',
                "Nome": "",
                "Desc": "",
                "QntS": "",
                "Valr": "",
                "Uber": "",
                "VUbr": "",
                "Link": [""],
            }],
        "Lixo": ""
    }
]